// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Pharmacy.Models
{
    public partial class Collection
    {
        public Collection()
        {
            CollectionItem = new HashSet<CollectionItem>();
        }

        public int CollectionId { get; set; }
        public string CollectionTlAr { get; set; }
        public string CollectionTlEn { get; set; }
        public int? CollectionSort { get; set; }
        public bool? IsActive { get; set; }

        public virtual ICollection<CollectionItem> CollectionItem { get; set; }
    }
}