// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Pharmacy.Models
{
    public partial class CollectionItem
    {
        public int CollectionItemId { get; set; }
        public int CollectionId { get; set; }
        public int ItemId { get; set; }

        public virtual Collection Collection { get; set; }
        public virtual Item Item { get; set; }
    }
}