// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Pharmacy.Models
{
    public partial class Configuration
    {
        public int ConfigurationId { get; set; }
        [RegularExpression("^[0-9]+$", ErrorMessage = " Accept Number Only")]
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Facebook { get; set; }
        [RegularExpression("^[0-9]+$", ErrorMessage = " Accept Number Only")]
        public string WhatsApp { get; set; }
        public string LinkedIn { get; set; }
        public string Instgram { get; set; }
        public string Twitter { get; set; }
    }
}