    // <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pharmacy.Models
{
    public partial class Country
    {
        public Country()
        {
            City = new HashSet<City>();
    
        }

        public int CountryId { get; set; }
        public string CountryTlAr { get; set; }
        public string CountryTlEn { get; set; }
        public string CountryPic { get; set; }
        public bool? CountryIsActive { get; set; }
        public int? CountryOrderIndex { get; set; }

        public virtual ICollection<City> City { get; set; }
    }
}