// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Pharmacy.Models
{
    public partial class HomeSliderType
    {
        public HomeSliderType()
        {
            HomeSlider = new HashSet<HomeSlider>();
        }

        public int HomeSliderTypeId { get; set; }
        public string HomeSliderTypeTlAr { get; set; }
        public string HomeSliderTypeTlEn { get; set; }

        public virtual ICollection<HomeSlider> HomeSlider { get; set; }
    }
}