// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Pharmacy.Models
{
    public partial class HomeSlider
    {
        public int HomeSliderId { get; set; }
        public string HomeSliderPic { get; set; }
        public int? HomeSliderTypeId { get; set; }
        public string HomeSliderEntityId { get; set; }
        public virtual HomeSliderType HomeSliderType { get; set; }
    }
}