// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Pharmacy.Models
{
    public partial class Item
    {
        public Item()
        {
            CollectionItem = new HashSet<CollectionItem>();
            ItemImage = new HashSet<ItemImage>();
            OrderItem = new HashSet<OrderItem>();
            Cart = new HashSet<Cart>();
        }

        public int ItemId { get; set; }
        public string ItemTlAr { get; set; }
        public string ItemTlEn { get; set; }
        public double? Price { get; set; }
        public int? BrandId { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public bool? IsActive { get; set; }
        public int CategoryId { get; set; }
        public string ItemPic { get; set; }
        public int? Stock { get; set; }

        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<CollectionItem> CollectionItem { get; set; }
        public virtual ICollection<ItemImage> ItemImage { get; set; }
        public virtual ICollection<OrderItem> OrderItem { get; set; }
        public virtual ICollection<Cart> Cart { get; set; }
    }
}