// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Pharmacy.Models
{
    public partial class Newsletter
    {
        public int NewsletterId { get; set; }
        public string Email { get; set; }
        public DateTime? Date { get; set; }


    }
}