// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable disable

namespace Pharmacy.Models
{
    public partial class Order
    {
        public Order()
        {
            OrderItem = new HashSet<OrderItem>();
        }

        public int OrderId { get; set; }
        public DateTime? OrderDate { get; set; }
        public string OrderSerial { get; set; }
        public double? Total { get; set; }
        public int? CustomerId { get; set; }
        public string Addrerss { get; set; }
        public bool? Closed { get; set; }
        public double DeliveryCost { get; set; }
        public bool ispaid { get; set; }
        public int PaymentMethodId { get; set; }
        public string Remarks { get; set; }
        public string payment_type { get; set; }
        public string PaymentID { get; set; }
        public string Result { get; set; }
        public DateTime? PostDate { get; set; }
        public string TranID { get; set; }
        public string Ref { get; set; }
        public string TrackID { get; set; }
        public string Auth { get; set; }
        [JsonIgnore]
        public virtual Customer Customer { get; set; }
        public int? DeliveryId { get; set; }
        [JsonIgnore]
        public virtual Delivery Delivery { get; set; }
        public virtual ICollection<OrderItem> OrderItem { get; set; }
    }
}