// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Pharmacy.Models
{
    public partial class PaymentMethod
    {
        public int PaymentMethodId { get; set; }
        public string PaymentMethodTlAr { get; set; }
        public string PaymentMethodTlEn { get; set; }
    }
}