// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable disable

namespace Pharmacy.Models
{
    public partial class Section
    {
       
        public int SectionId { get; set; }
        public string SectionTlAr { get; set; }
        public string SectionTlEn { get; set; }
        public string SectionPic { get; set; }
        public int? SectionSort { get; set; }
        public bool? IsActive { get; set; }
        public virtual ICollection<Category> Categories { get; set; }

    }
}